<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PackageId>Basalt</PackageId>
    <Version>1.1.0</Version>
    <Authors>Vanderhell</Authors>
    <Description>Local durable background jobs, scheduling and workflow engine for .NET applications.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>jobs;durable;background;WPF;scheduling;workflow</PackageTags>
    <RepositoryUrl>https://github.com/Vanderhell/Basalt.NET</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BasaltCore.Native\BasaltCore.Native.csproj" PrivateAssets="all" />
    <PackageReference Include="System.Memory" Version="4.5.5" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="..\build-release\Release\basalt_core_shared.dll" Condition="Exists('..\build-release\Release\basalt_core_shared.dll')" Pack="true" PackagePath="runtimes\win-x64\native" />
    <None Include="..\BasaltCore.Native\bin\Release\netstandard2.0\BasaltCore.Native.dll" Pack="true" PackagePath="lib\netstandard2.0" />
    <None Include="..\BasaltCore.Native\bin\Release\net8.0\BasaltCore.Native.dll" Pack="true" PackagePath="lib\net8.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug' And Exists('..\build\Debug\basalt_core_shared.dll')">
    <None Include="..\build\Debug\basalt_core_shared.dll" Link="basalt_core_shared.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' != 'Debug' And Exists('..\build-release\Release\basalt_core_shared.dll')">
    <None Include="..\build-release\Release\basalt_core_shared.dll" Link="basalt_core_shared.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
